'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

fibo1 = 1
fibo2 = 2
sum = 0
while True:
 if fibo2 % 2 == 0:
	sum = sum + fibo2
 swap = fibo1
 fibo1 = fibo2
 fibo2 = swap + fibo2

 if fibo2 > 4000000:
	break

print "Sum of Fibonacci series is: ", sum
